server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:h2:./java_project_73
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: INFO
    web: DEBUG